function showHeroTop(){if(location.hash)history.replaceState(history.state,'',location.pathname+location.search);window.scrollTo({top:0,left:0,behavior:'instant'});requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'instant'}));}
const body=document.body;
let selected='neutral';
const names={neutral:'Оба мира',art:'SoulArt / KRTY',digital:'RE: FORM'};
const captions={neutral:'Превращаю идеи в визуальные истории.<br>И даю им жизнь.',art:'Живой рисунок. Смелая типографика.<br>Дизайн с характером.',digital:'Один человек. Дизайн. Код. ИИ.<br>Идеи, с которыми можно взаимодействовать.'};
function preview(world){body.dataset.preview=world;document.getElementById('hero-caption').innerHTML=captions[world];window.dispatchEvent(new CustomEvent('world-preview',{detail:world}));}
function choose(world,scroll=false){selected=world;body.dataset.world=world;preview(world);for(const key of Object.keys(names))document.getElementById(key+'-content').hidden=key!==world;document.querySelectorAll('[data-switch]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.switch===world)));document.getElementById('section-kicker').textContent={neutral:'THE SPACE BETWEEN',art:'ART WITH ATTITUDE',digital:'RE: FORM / PERSONAL CREATIVE OS'}[world];document.getElementById('world-status').textContent='Выбрано направление: '+names[world];if(scroll)showHeroTop();}
document.querySelectorAll('[data-pick]').forEach(b=>{for(const text of b.children){text.addEventListener('pointerenter',()=>{if(matchMedia('(hover:hover)').matches)preview(b.dataset.pick)});text.addEventListener('pointerleave',()=>preview(selected));}b.addEventListener('focus',()=>preview(b.dataset.pick));b.addEventListener('click',()=>choose(b.dataset.pick,true));b.addEventListener('blur',()=>preview(selected));});
document.querySelector('.choices').addEventListener('pointerleave',()=>preview(selected));document.querySelector('.hero').addEventListener('focusout',e=>{if(!e.relatedTarget||!document.querySelector('.hero').contains(e.relatedTarget))preview(selected)});
document.querySelectorAll('[data-switch]').forEach(b=>b.addEventListener('click',()=>choose(b.dataset.switch,true)));
document.querySelector('.world-reset').addEventListener('click',()=>{choose('neutral');showHeroTop()});
const heroMotion=document.querySelector('.hero');
function resetHeroMotion(){heroMotion.style.setProperty('--motion-x','0px');heroMotion.style.setProperty('--motion-y','0px');}
heroMotion.addEventListener('pointermove',e=>{if(body.dataset.preview!=='digital'||e.pointerType==='touch'||matchMedia('(prefers-reduced-motion:reduce)').matches){resetHeroMotion();return;}const rect=heroMotion.getBoundingClientRect();heroMotion.style.setProperty('--motion-x',((e.clientX-rect.left)/rect.width-.5)*24+'px');heroMotion.style.setProperty('--motion-y',((e.clientY-rect.top)/rect.height-.5)*16+'px');});
heroMotion.addEventListener('pointerleave',resetHeroMotion);
const projects=[{title:'Brand Book GxSoul/KRTY',description:'Айдентика и руководство по визуальному стилю.',image:'brandbook.jpg',type:'BRAND IDENTITY',url:'https://www.behance.net/gallery/246885793/Brand-Book-GxSoulKRTY'},{title:'XFit Rebranding',description:'Концепция ребрендинга · учебный проект.',image:'xfit.jpg',type:'REBRANDING',url:'https://www.behance.net/gallery/249997653/XFit-Rebranding'},{title:'Portfolio Website',description:'Сайт-портфолио · учебный проект.',image:'portfolio.jpg',type:'DIGITAL DESIGN',url:'https://www.behance.net/gallery/251160601/Portfolio-Website'},{title:'Journal',description:'Журнальная вёрстка и редакционный дизайн.',image:'journal.jpg',type:'EDITORIAL DESIGN',url:'https://www.behance.net/gallery/229126569/Journal-Full-fledged-layout-of-the-magazine'}];
function projectCard(p){const a=document.createElement('a');a.className='project-card';a.href=p.url;a.target='_blank';a.rel='noopener noreferrer';const img=document.createElement('img');img.src='assets/profile/'+p.image;img.alt=p.title;img.loading='lazy';const meta=document.createElement('div');meta.className='project-meta';const copy=document.createElement('div');const tag=document.createElement('span');tag.textContent=p.type;const title=document.createElement('h3');title.textContent=p.title;const desc=document.createElement('p');desc.textContent=p.description;copy.append(tag,title,desc);const arrow=document.createElement('b');arrow.textContent='↗';meta.append(copy,arrow);a.append(img,meta);return a;}
document.getElementById('art-projects').append(...projects.map(projectCard));document.querySelector('.neutral-projects').append(...[projects[0],projects[2]].map(projectCard));document.getElementById('digital-projects').append(projectCard(projects[2]));
function panel(name){document.querySelectorAll('[data-app-panel]').forEach(s=>s.hidden=s.dataset.appPanel!==name);document.querySelectorAll('.app-nav [data-panel]').forEach(b=>{b.classList.toggle('active',b.dataset.panel===name);b.setAttribute('aria-pressed',String(b.dataset.panel===name))});document.getElementById('app-breadcrumb').textContent='RE: FORM / '+{overview:'Студия',projects:'Проекты',notes:'Заметки',focus:'Фокус',play:'Лаборатория идей'}[name];}
document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>panel(b.dataset.panel)));
const storageKey='kartaamigo-reform-workspace-v1';let state={notes:[],tasks:[]};let storageAvailable=true;
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved&&Array.isArray(saved.notes)&&Array.isArray(saved.tasks)){state.notes=saved.notes.filter(n=>typeof n.id==='string'&&typeof n.title==='string'&&typeof n.body==='string'&&typeof n.date==='string');state.tasks=saved.tasks.filter(t=>typeof t.id==='string'&&typeof t.text==='string'&&typeof t.done==='boolean')}}catch{storageAvailable=false}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));storageAvailable=true;return true}catch{storageAvailable=false;document.getElementById('storage-message').textContent='Браузер не разрешил сохранение. Заметки доступны, пока открыта страница.';return false}}
function uniqueId(){return globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}
function renderNotes(){const list=document.getElementById('notes-list');list.replaceChildren();document.getElementById('note-count').textContent=state.notes.length;if(!state.notes.length){const p=document.createElement('p');p.className='empty-state';p.textContent='Здесь пока тихо. Оставь первую идею - она будет ждать тебя при следующем посещении.';list.append(p)}for(const n of [...state.notes].reverse()){const card=document.createElement('article');card.className='note';const title=document.createElement('h4');title.textContent=n.title;const p=document.createElement('p');p.textContent=n.body;const bottom=document.createElement('div');bottom.className='note-bottom';const time=document.createElement('time');time.dateTime=n.date;time.textContent=new Date(n.date).toLocaleDateString('ru-RU',{day:'numeric',month:'short',timeZone:'Europe/Moscow'});const del=document.createElement('button');del.type='button';del.textContent='Удалить';del.setAttribute('aria-label','Удалить заметку '+n.title);del.addEventListener('click',()=>{state.notes=state.notes.filter(x=>x.id!==n.id);save();renderNotes()});bottom.append(time,del);card.append(title,p,bottom);list.append(card)}}
document.getElementById('note-form').addEventListener('submit',e=>{e.preventDefault();const title=document.getElementById('note-title').value.trim(),text=document.getElementById('note-body').value.trim();if(!title||!text)return;state.notes.push({id:uniqueId(),title,body:text,date:new Date().toISOString()});const ok=save();renderNotes();e.target.reset();document.getElementById('storage-message').textContent=ok?'Идея сохранена на этом устройстве.':'Заметка добавлена. Сохранение между посещениями недоступно.'});
function renderTasks(){const list=document.getElementById('task-list');list.replaceChildren();for(const t of state.tasks){const row=document.createElement('div');row.className='task';const label=document.createElement('label');const check=document.createElement('input');check.type='checkbox';check.checked=t.done;check.addEventListener('change',()=>{t.done=check.checked;save()});const text=document.createElement('span');text.textContent=t.text;label.append(check,text);const del=document.createElement('button');del.className='task-delete';del.type='button';del.textContent='×';del.setAttribute('aria-label','Удалить задачу '+t.text);del.addEventListener('click',()=>{state.tasks=state.tasks.filter(x=>x.id!==t.id);save();renderTasks()});row.append(label,del);list.append(row)}}
document.getElementById('task-form').addEventListener('submit',e=>{e.preventDefault();const input=document.getElementById('task-input');const text=input.value.trim();if(!text)return;state.tasks.push({id:uniqueId(),text,done:false});save();renderTasks();input.value=''});
let remaining=25*60,deadline=null,interval=null;
function updateTimer(){if(deadline)remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));document.getElementById('timer').textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');if(remaining===0&&deadline){clearInterval(interval);interval=null;deadline=null;document.getElementById('timer-toggle').textContent='Ещё сессия';document.getElementById('timer-status').textContent='Сессия завершена. Время выдохнуть.'}}
document.getElementById('timer-toggle').addEventListener('click',()=>{if(deadline){updateTimer();deadline=null;clearInterval(interval);interval=null;document.getElementById('timer-toggle').textContent='Продолжить';document.getElementById('timer-status').textContent='Пауза. Возвращайся, когда будешь готова.'}else{if(remaining===0)remaining=1500;deadline=Date.now()+remaining*1000;interval=setInterval(updateTimer,250);document.getElementById('timer-toggle').textContent='Пауза';document.getElementById('timer-status').textContent='Всё внимание - одной идее.'}updateTimer()});
document.getElementById('timer-reset').addEventListener('click',()=>{clearInterval(interval);interval=null;deadline=null;remaining=1500;updateTimer();document.getElementById('timer-toggle').textContent='Начать';document.getElementById('timer-status').textContent='Отключи лишнее. Выбери одну задачу.'});
renderNotes();renderTasks();if(!storageAvailable)document.getElementById('storage-message').textContent='Сохранение в этом браузере недоступно. Заметки останутся до закрытия страницы.';
