import * as THREE from './assets/three.module.js';
const host=document.getElementById('bunny-3d');
try{
const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;host.append(renderer.domElement);
const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(32,1,.1,100);camera.position.set(0,.6,9.2);camera.lookAt(0,.4,0);
scene.add(new THREE.HemisphereLight(0xe9f4ff,0x3c1026,2.1));const key=new THREE.DirectionalLight(0xffffff,5);key.position.set(-4,5,5);scene.add(key);const pink=new THREE.PointLight(0xff087e,60,15);pink.position.set(3,-.4,3);scene.add(pink);const edge=new THREE.DirectionalLight(0xff61af,4);edge.position.set(2,4,-2);scene.add(edge);
const bunny=new THREE.Group();bunny.position.y=-.35;scene.add(bunny);
const material=new THREE.MeshPhysicalMaterial({color:0xb95480,metalness:.53,roughness:.29,clearcoat:1,clearcoatRoughness:.2});const inner=new THREE.MeshStandardMaterial({color:0x6c294c,metalness:.35,roughness:.4});const stitch=new THREE.MeshStandardMaterial({color:0xffeee6,roughness:.65});
function sphere(parent,x,y,z,sx,sy,sz,mat){const mesh=new THREE.Mesh(new THREE.SphereGeometry(1,48,36),mat);mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);parent.add(mesh);return mesh}
sphere(bunny,0,0,0,1.16,.8,.83,material);
const earL=new THREE.Group();earL.position.set(-.61,.7,0);earL.rotation.z=1.02;bunny.add(earL);sphere(earL,0,.65,0,.32,.87,.27,material);sphere(earL,0,.65,.235,.17,.62,.065,inner);const bentTip=sphere(bunny,-1.55,.88,0,.29,.4,.26,material);bentTip.rotation.z=-.25;
const earR=new THREE.Group();earR.position.set(.66,.7,-.05);earR.rotation.z=-.55;bunny.add(earR);sphere(earR,0,.68,0,.34,.83,.27,material);sphere(earR,0,.68,.23,.19,.59,.065,inner);
sphere(bunny,-1.05,-.65,.35,.42,.24,.35,material);sphere(bunny,1.05,-.65,.35,.42,.24,.35,material);
function line(parent,a,b,r,mat){const va=new THREE.Vector3(...a),vb=new THREE.Vector3(...b);const delta=vb.clone().sub(va);const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,delta.length(),12),mat);mesh.position.copy(va.clone().add(vb).multiplyScalar(.5));mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());parent.add(mesh)}
for(const x of [-.43,.43]){line(bunny,[x-.15,.34,.775],[x+.15,.02,.86],.039,stitch);line(bunny,[x+.15,.34,.775],[x-.15,.02,.86],.039,stitch);for(const t of [-.09,0,.09]){line(bunny,[x+t-.045,.18-t,.87],[x+t+.045,.18-t,.875],.009,inner)}}
const seam=new THREE.CatmullRomCurve3(Array.from({length:30},(_,i)=>{const y=-.7+i*.057;const z=.835*Math.sqrt(Math.max(.02,1-y*y/1.06));return new THREE.Vector3(.02,y,z+.007)}));const seamMesh=new THREE.Mesh(new THREE.TubeGeometry(seam,40,.01,5,false),inner);bunny.add(seamMesh);
const tab=new THREE.Mesh(new THREE.BoxGeometry(.17,.2,.2),material);tab.position.set(0,.91,0);bunny.add(tab);
const retro=new THREE.Group();retro.position.set(1.75,1.5,-.7);retro.rotation.set(.08,-.4,-.23);scene.add(retro);const shell=new THREE.MeshStandardMaterial({color:0xcbbfc6,metalness:.65,roughness:.3});const screenMat=new THREE.MeshStandardMaterial({color:0x17131c,metalness:.2,roughness:.4});const machine=new THREE.Mesh(new THREE.BoxGeometry(.7,.85,.15),shell);retro.add(machine);const screen=new THREE.Mesh(new THREE.BoxGeometry(.51,.38,.025),screenMat);screen.position.set(0,.14,.09);retro.add(screen);const pixels=new THREE.MeshBasicMaterial({color:0xff3a8e});for(let y=0;y<4;y++)for(let x=0;x<7;x++){if((x+y)%3===0)continue;const px=new THREE.Mesh(new THREE.BoxGeometry(.04,.04,.01),pixels);px.position.set(-.2+x*.063,.24-y*.068,.11);retro.add(px)}for(const [x,y] of [[-.16,-.18],[-.16,-.28],[-.24,-.23],[-.08,-.23],[.16,-.2],[.23,-.28]]){const b=new THREE.Mesh(new THREE.BoxGeometry(.065,.065,.035),screenMat);b.position.set(x,y,.1);retro.add(b)}
const chunks=new THREE.Group();chunks.position.set(-1.8,-.2,-.8);scene.add(chunks);for(let i=0;i<9;i++){const cube=new THREE.Mesh(new THREE.BoxGeometry(.15,.15,.15),i%3===0?pixels:shell);cube.position.set((i%3)*.17,Math.floor(i/3)*.17,Math.sin(i)*.15);chunks.add(cube)}
let targetX=0,targetY=0,shown=true;const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;document.querySelector('.hero').addEventListener('pointermove',e=>{if(reduced)return;const r=e.currentTarget.getBoundingClientRect();targetY=(e.clientX-r.left-r.width/2)/r.width*.25;targetX=(e.clientY-r.top-r.height/2)/r.height*.1});document.querySelector('.hero').addEventListener('pointerleave',()=>{targetX=0;targetY=0});new IntersectionObserver(entries=>{shown=entries[0].isIntersecting}).observe(host);
function resize(){const {width,height}=host.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();renderer.render(scene,camera)}new ResizeObserver(resize).observe(host);resize();
renderer.setAnimationLoop(t=>{if(!shown)return;bunny.rotation.y+=(targetY-bunny.rotation.y)*.05;bunny.rotation.x+=(targetX-bunny.rotation.x)*.05;if(!reduced){bunny.position.y=-.35+Math.sin(t*.0008)*.05;retro.position.y=1.5+Math.sin(t*.0007)*.07;chunks.rotation.y=t*.00016;chunks.rotation.z=.25}renderer.render(scene,camera)});
const gameHost=document.getElementById('game-scene');const gameRenderer=new THREE.WebGLRenderer({alpha:true,antialias:true});gameRenderer.setPixelRatio(Math.min(devicePixelRatio,1.5));gameRenderer.setClearColor(0x000000,0);gameRenderer.toneMapping=THREE.ACESFilmicToneMapping;gameRenderer.toneMappingExposure=1.4;gameHost.append(gameRenderer.domElement);const gameScene=new THREE.Scene();gameScene.add(new THREE.HemisphereLight(0xffffff,0x894467,3));const gameLight=new THREE.DirectionalLight(0xffffff,5);gameLight.position.set(-2,4,5);gameScene.add(gameLight);const gamePink=new THREE.PointLight(0xff287c,30);gamePink.position.set(2,0,4);gameScene.add(gamePink);const gameBunny=bunny.clone();gameBunny.scale.setScalar(.55);gameBunny.position.set(0,-.65,0);gameScene.add(gameBunny);const gameCamera=new THREE.PerspectiveCamera(38,1,.1,100);gameCamera.position.set(0,1,7);gameCamera.lookAt(0,.5,0);let gameVisible=false,gameTarget=0,jumpAt=0,jumpHeight=1.8;new IntersectionObserver(entries=>gameVisible=entries[0].isIntersecting).observe(gameHost);const gameResize=()=>{const r=gameHost.getBoundingClientRect();if(!r.width||!r.height)return;gameRenderer.setSize(r.width,r.height);gameCamera.aspect=r.width/r.height;gameCamera.updateProjectionMatrix();gameRenderer.render(gameScene,gameCamera)};new ResizeObserver(gameResize).observe(gameHost);window.addEventListener('game-collect',e=>{const visibleHeight=2*Math.tan(THREE.MathUtils.degToRad(19))*7;gameTarget=e.detail.x*visibleHeight*gameCamera.aspect;jumpHeight=1.8+e.detail.y*visibleHeight;jumpAt=performance.now()});window.addEventListener('game-reset',()=>{gameTarget=0;jumpAt=0});gameRenderer.setAnimationLoop(t=>{if(!gameVisible)return;gameBunny.position.x+=(gameTarget-gameBunny.position.x)*.13;const elapsed=t-jumpAt;gameBunny.position.y=-.65+(!reduced&&elapsed>=0&&elapsed<600?Math.sin(elapsed/600*Math.PI)*jumpHeight:0);gameBunny.rotation.z=!reduced&&elapsed<600?Math.sin(elapsed/600*Math.PI)*-.12:0;gameRenderer.render(gameScene,gameCamera)});
}catch(error){host.classList.add('scene-fallback');host.setAttribute('data-fallback','true');console.warn('3D unavailable:',error.message)}

