const { chromium } = require('C:/Users/1/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const variant = process.argv[2] === 'compact';
  const prefix = variant ? 'studio-compact' : 'studio';
  const url = 'http://127.0.0.1:8893/personal-portfolio-concept/' + (variant ? 'folders-compact.html?v=compact-1' : 'folders.html?v=studio-1');
  await page.goto(url);
  await page.locator('.studio-hat').waitFor();
  await page.waitForTimeout(400);
  await page.waitForFunction(() => [...document.querySelectorAll('.studio-center img')].every(image => image.complete && image.naturalWidth));
  assert.equal(await page.locator('.studio-icon').count(), 3);
  assert(!await page.locator('.studio-greeting').isVisible());
  await page.screenshot({ path: path.join(__dirname, prefix + '-neutral.png') });
  await page.locator('.studio-hat').hover();
  await page.waitForTimeout(500);
  assert(await page.locator('.studio-greeting').isVisible());
  await page.screenshot({ path: path.join(__dirname, prefix + '-greeting.png') });
  await page.keyboard.press('Escape');
  await page.waitForTimeout(350);
  assert(!await page.locator('.studio-greeting').isVisible());
  await page.locator('.folder-art .folder-launch').click();
  assert.equal(await page.getAttribute('body', 'data-world'), 'art');
  assert(!await page.locator('.studio-center').isVisible());
  await page.evaluate(() => choose('neutral'));
  for (const width of [320,390,800,1024,1920]) {
    await page.mouse.move(1, 1);
    await page.setViewportSize({ width, height: 1000 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Overflow ${width}`);
    await page.locator('.studio-hat').hover();
    await page.waitForTimeout(500);
    const box = await page.locator('.studio-greeting').boundingBox();
    assert(box.x >= 0 && box.x + box.width <= width, `Greeting fits ${width}`);
    assert(await page.locator('.studio-greeting').evaluate(element => {
      const style = getComputedStyle(element);
      const bounds = element.getBoundingClientRect();
      const lastText = element.querySelector('small').getBoundingClientRect();
      return !['auto', 'scroll'].includes(style.overflowY) && lastText.bottom <= bounds.bottom;
    }), `Greeting has no scrollbar or clipped text at ${width}`);
    await page.keyboard.press('Escape');
    await page.waitForTimeout(350);
  }
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert.equal(await page.locator('.studio-icon').first().evaluate(element => getComputedStyle(element).animationName), 'none');
  await page.setViewportSize({ width:1440,height:900 });
  await page.mouse.move(1,1);
  await page.locator('.studio-hat').hover();
  assert(await page.locator('.studio-greeting').evaluate(element => element.getBoundingClientRect().top >= document.querySelector('body>header').getBoundingClientRect().bottom + 19), 'Greeting keeps gap from header');
  const mobile = await browser.newPage({ viewport: { width:390,height:844 },hasTouch:true,isMobile:true });
  await mobile.goto(url);
  await mobile.locator('.studio-hat').tap();
  await mobile.waitForTimeout(500);
  assert(await mobile.locator('.studio-greeting').isVisible());
  await mobile.screenshot({ path: path.join(__dirname, prefix + '-mobile.png') });
  await mobile.locator('.studio-greeting-close').tap();
  await mobile.waitForTimeout(350);
  assert(!await mobile.locator('.studio-greeting').isVisible());
  assert.deepEqual(errors, []);
  console.log('PASS: central art, three animated icons, greeting hover/touch/Escape, folder navigation, responsive layout and reduced motion');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
