const { chromium } = require('C:/Users/1/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
const path = require('node:path');

(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const url = 'http://127.0.0.1:8893/personal-portfolio-concept/';
  await page.goto(url + 'folders.html');
  await page.locator('.folder-item').first().waitFor();
  await page.waitForFunction(() => [...document.querySelectorAll('.folder-card img')].every(image => image.complete && image.naturalWidth > 0));
  const art = page.locator('.folder-art');
  const digital = page.locator('.folder-digital');
  assert.equal(await page.locator('.folder-item').count(), 2);
  assert(!await page.locator('.world-selector').isVisible(), 'Slider is removed from folder variant');
  assert.equal(await page.locator('.world-selector').evaluate(element => element.inert), true);
  assert(!/ползунок/i.test(await page.locator('.hero').innerText()));
  assert.equal(await art.getAttribute('data-open'), 'false');
  assert.equal(await digital.getAttribute('data-open'), 'false');
  assert.equal(await art.locator('.folder-card').first().evaluate(element => getComputedStyle(element).opacity), '0');
  assert(!await art.locator('.folder-enter').isVisible());
  assert(await page.locator('.folder-card img').evaluateAll(images => images.every(image => image.complete && image.naturalWidth > 0)), 'Project covers load');
  await page.screenshot({ path: path.join(__dirname, 'folders-closed.png') });
  await art.locator('.folder-launch').hover();
  await page.waitForTimeout(800);
  assert.equal(await art.getAttribute('data-open'), 'true');
  assert.equal(await digital.getAttribute('data-open'), 'false');
  assert.equal(await page.getAttribute('body', 'data-world'), 'neutral');
  assert.equal(await art.locator('.folder-card').first().evaluate(element => getComputedStyle(element).opacity), '1');
  await page.screenshot({ path: path.join(__dirname, 'folders-art-hover.png') });
  await digital.locator('.folder-launch').hover();
  await page.waitForTimeout(800);
  assert.equal(await art.getAttribute('data-open'), 'false');
  assert.equal(await digital.getAttribute('data-open'), 'true');
  await page.screenshot({ path: path.join(__dirname, 'folders-reform-hover.png') });
  await page.mouse.move(720, 350);
  await art.locator('.folder-launch').focus();
  await art.locator('.folder-launch').press('Enter');
  assert.equal(await page.getAttribute('body', 'data-world'), 'art');
  assert(!await page.locator('.folder-choices').isVisible());
  assert(!await page.locator('.world-selector').isVisible());
  await page.keyboard.press('Escape');
  await page.waitForTimeout(100);
  assert.equal(await page.getAttribute('body', 'data-world'), 'neutral');
  assert.equal(await art.locator('.folder-launch').evaluate(element => element === document.activeElement), true);
  await digital.locator('.folder-launch').click();
  assert.equal(await page.getAttribute('body', 'data-world'), 'digital', 'Folder click opens Reform directly');
  assert.equal(await page.locator('.digital-project').count(), 2);
  assert.equal(await page.locator('.digital-project-screens img').count(), 5);
  assert.equal(await page.locator('.work-layout').isVisible(), false, 'Old concept covers hidden on Reform side');
  await page.locator('.digital-project-screens button').first().click();
  assert(await page.locator('.project-lightbox').isVisible());
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator('.project-lightbox-controls span').innerText(), '2 / 3');
  await page.keyboard.press('Escape');
  assert(!await page.locator('.project-lightbox').isVisible());
  assert.equal(await page.getAttribute('body', 'data-world'), 'digital', 'Closing screen preview keeps Reform selected');
  await page.locator('.digital-project').last().locator('button').last().click();
  await page.waitForFunction(() => document.querySelector('.project-lightbox img').complete && document.querySelector('.project-lightbox img').naturalWidth > 0);
  await page.screenshot({ path: path.join(__dirname, 'reform-life-preview.png') });
  await page.keyboard.press('Escape');
  await page.locator('.digital-project').first().scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(__dirname, 'reform-real-projects.png') });
  await page.evaluate(() => choose('neutral'));
  for (const width of [320,390,800,1024,1920]) {
    await page.setViewportSize({ width, height: width <= 800 ? 844 : 1000 });
    await page.mouse.move(1, 1);
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Overflow at ${width}`);
    for (const item of [art,digital]) {
      await item.locator('.folder-launch').hover();
      await page.waitForTimeout(650);
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Hover overflow at ${width}`);
    }
  }
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert.equal(await art.locator('.folder-card').first().evaluate(element => getComputedStyle(element).transitionDuration), '0s');
  await page.goto(url + 'combined.html');
  assert.equal(await page.locator('.folder-choices').count(), 0, 'Original site remains separate');
  assert(await page.locator('.world-intros').isVisible());
  assert(await page.locator('.world-selector').isVisible(), 'Original site keeps its slider');
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  mobile.on('pageerror', error => errors.push(error.message));
  await mobile.goto(url + 'folders.html');
  await mobile.locator('.folder-art .folder-launch').waitFor();
  await mobile.locator('.folder-art .folder-launch').tap();
  assert.equal(await mobile.getAttribute('body', 'data-world'), 'art');
  await mobile.waitForTimeout(700);
  await mobile.screenshot({ path: path.join(__dirname, 'folders-mobile.png') });
  await mobile.locator('.world-reset').tap();
  await mobile.locator('.folder-digital .folder-launch').tap();
  assert.equal(await mobile.getAttribute('body', 'data-world'), 'digital');
  await mobile.locator('.digital-project').first().scrollIntoViewIfNeeded();
  assert(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Real projects fit mobile');
  await mobile.screenshot({ path: path.join(__dirname, 'reform-real-mobile.png') });
  assert.deepEqual(errors, []);
  console.log('PASS: separate duplicate, no slider, hover previews, direct folder clicks, two actual projects/five screens, lightbox, keyboard, touch, five sizes');
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
